import warnings

import ccxt
from atc_trading_bot.pipeline_warning import PipelineWarning


class TradingMixin:
    """Mixin for paper trading execution via exchange testnet.

    Connects to an exchange's testnet (sandbox) and executes orders
    based on signals generated by the pipeline. All trades are paper
    trades -- no real funds are at risk.

    Typical usage:
        bot.connect_testnet(api_key, secret)
        bot.execute_signal()
        bot.get_balance()
        bot.get_open_positions()
    """

    def _require_signals(self) -> bool:
        """Check that signals have been generated."""
        if getattr(self, "signals", None) is None:
            warnings.warn(
                "No signals available. Call generate_signals first.",
                PipelineWarning,
            )
            return False
        return True

    def _require_testnet(self) -> bool:
        """Check that a testnet exchange connection has been established."""
        if getattr(self, "testnet_exchange", None) is None:
            warnings.warn(
                "No testnet connected. Call connect_testnet first.",
                PipelineWarning,
            )
            return False
        return True

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.testnet_exchange: ccxt.Exchange | None = None
        self.last_order: dict | None = None

    def connect_testnet(self, api_key: str, secret: str,
                        exchange_id: str = "binanceus") -> "TradingMixin":
        """Connect to an exchange's testnet (sandbox) for paper trading.

        Args:
            api_key: Testnet API key.
            secret: Testnet API secret.
            exchange_id: CCXT exchange identifier. Default: "binanceus".

        Returns:
            self for method chaining.
        """
        exchange_cls = getattr(ccxt, exchange_id, None)
        if exchange_cls is None:
            warnings.warn(
                f"Unknown exchange: {exchange_id}. Check CCXT docs.",
                PipelineWarning,
            )
            return self

        self.testnet_exchange = exchange_cls({
            "apiKey": api_key,
            "secret": secret,
            "enableRateLimit": True,
        })
        self.testnet_exchange.set_sandbox_mode(True)
        return self

    def execute_signal(self, symbol: str = "BTC/USDT",
                       amount: float = 0.001) -> "TradingMixin":
        """Execute a paper trade based on the latest signal.

        Reads the signal from self.signals and places a market order
        on the connected testnet exchange.

        Args:
            symbol: Trading pair to execute on. Default: "BTC/USDT".
            amount: Order size in base currency. Default: 0.001.

        Returns:
            self for method chaining.
        """
        if not self._require_signals():
            return self
        if not self._require_testnet():
            return self

        signal = self.signals.get("signal")
        if signal not in ("buy", "sell"):
            warnings.warn(
                f"Signal is '{signal}', no order to execute.",
                PipelineWarning,
            )
            return self

        try:
            order = self.testnet_exchange.create_order(
                symbol=symbol,
                type="market",
                side=signal,
                amount=amount,
            )
            self.last_order = order
        except Exception as exc:
            warnings.warn(
                f"Order execution failed: {exc}",
                PipelineWarning,
            )

        return self

    def get_balance(self) -> dict | None:
        """Fetch the testnet account balance.

        Returns:
            Balance dict from CCXT, or None if exchange is not connected.
        """
        if not self._require_testnet():
            return None

        try:
            return self.testnet_exchange.fetch_balance()
        except Exception as exc:
            warnings.warn(
                f"Failed to fetch balance: {exc}",
                PipelineWarning,
            )
            return None

    def get_open_positions(self) -> list | None:
        """List open positions on the testnet.

        Returns:
            List of position dicts from CCXT, or None if exchange
            is not connected.
        """
        if not self._require_testnet():
            return None

        try:
            return self.testnet_exchange.fetch_positions()
        except Exception as exc:
            warnings.warn(
                f"Failed to fetch positions: {exc}",
                PipelineWarning,
            )
            return None
